name: "Dependency Review"

on:
  push:
    branches:
      - master
    paths:
      - "go.mod"
  schedule:
    - cron: '0 0 * * 1'
  workflow_call:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3.1.4
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: on-failure
          license-check: false
          base-ref: ${{ github.ref }}
          head-ref: ${{ github.ref }}
