on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "go.mod"
  pull_request:
    branches:
      - "**"
    paths:
      - "**.go"
      - "go.mod"
  workflow_dispatch:

name: tests
jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"
          echo "dir=$HOME/.cache/teler-waf" >> "$GITHUB_OUTPUT"
        id: cache
      - uses: actions/cache@v4
        with:
          path: ${{ steps.cache.outputs.dir }}
          key: teler-resources-${{ steps.cache.outputs.date }}
      - run: make ci

  codecov:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: make cover
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/teler-coverage.out

  golangci:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=5m
        
  semgrep:
    runs-on: ubuntu-latest
    needs: tests
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
           SEMGREP_RULES: auto

  codeql:
    needs: tests
    uses: ./.github/workflows/codeql.yaml

  bearer:
    needs: tests
    uses: ./.github/workflows/bearer.yaml
    with:
      diff: ${{ github.event_name == 'pull_request' && true || false }}

  regression:
    needs: tests
    uses: ./.github/workflows/regression.yaml

  license-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go install -v github.com/palantir/go-license@latest
      - run: make license-verify

  dependency-review:
    if: (github.event_name == 'pull_request')
    uses: ./.github/workflows/dependency-review.yaml